# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/cache@v4
        with:
          cache: 'npm'
          path:
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys:  ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
         node-version:
           ${{ matrix.node-version }}
         cache: 'npm'
      - run: npm install
      - run: npm install supabase
      - run: npm install vercel
      - run: npm ci
      - run: npm run build --if-present
      - run: npm dev
